<?xml version="1.0" standalone="yes"?>
<!DOCTYPE Options [
	<!ELEMENT options (connection*)>
	<!ELEMENT connection (driver, host, port, username, password, tablemap)>
	<!ELEMENT driver (#PCDATA)>
	<!ELEMENT host (#PCDATA)>
	<!ELEMENT port (#PCDATA)>
	<!ELEMENT username (#PCDATA)>
	<!ELEMENT password (#PCDATA)>
	<!ELEMENT tablemap (prices, info)>
	<!ELEMENT prices (name, pricefields)>
	<!ELEMENT pricesfields (date, symbol, open, high, low, close, volume)>
	<!ELEMENT info (name, infofields)>
	<!ELEMENT name (#PCDATA)>
	<!ELEMENT infofields (symbol, name)>
	<!ELEMENT symbol (#PCDATA)>
	<!ELEMENT date (#PCDATA)>
	<!ELEMENT open (#PCDATA)>
	<!ELEMENT high (#PCDATA)>
	<!ELEMENT low (#PCDATA)>
	<!ELEMENT close (#PCDATA)>
	<!ELEMENT volume (#PCDATA)>
]>

<options>
	<connection name="default">
		<driver>org.gjt.mm.mysql.Driver</driver>
		<host>db</host>
		<port>3306</port>
		<username>shares</username>
		<password>money5me</password>
		<tablemap>
			<prices>
				<name>shares</name>
				<pricesfields>
					<date>date</date>
					<symbol>symbol</symbol>
					<open>open</open>
					<high>high</high>
					<low>low</low>
					<close>close</close>
					<volume>volume</volume>
				</pricesfields>
			</prices>
			<info>
				<name>lookup</name>
				<infofields>
					<symbol>symbol</symbol>
					<name>name</name>
				</infofields>
			</info>
		</tablemap>
	</connection>
</options>
